---
- name: Base | Copy .env to shared location
  file: path={{ app_path }}/shared/ owner={{ app.user }} group={{ app.user }} state=directory

- name: Base | Copy .env to shared location
  copy: src=files/.env.{{ server_env }} dest={{ app_path }}/shared/.env owner={{ app.user }} group={{ app.user }} force=no backup=yes