---
- name: Copy .env to shared location
  file: path={{ app_path }}/shared/ owner={{ app_user }} group={{ app_user }} state=directory

- name: Copy .env to shared location
  copy: src=files/.env.{{ server_env }} dest={{ app_path }}/shared/.env owner={{ app_user }} group={{ app_user }} force=yes backup=yes
