---
- name: Ensure the directory for .env exists
  file: path={{ dotenv.path }} owner={{ dotenv.user }} group={{ dotenv.group }} state=directory

- name: Create or update .env file
  template: src=dotenv.j2 dest={{ dotenv.path }}/.env owner={{ dotenv.user }} group={{ dotenv.group }} backup=yes
